from datetime import datetime

date_time = datetime.now().strftime("%Y%m%d%H%M%S")
print(f"Sekarang Tanggal dan Waktunya adalah {date_time}")
print("Nama Saya Falih")
print("Update 1")
print("Update 2")
print("Update 3")
print("Update 4")
print("Update 5")
print("Update 6")
print("Update 7")
print("Update 8")
print("Update 9")
print("Update 10")
print("Update 11")
print("Update 12")
