from datetime import datetime

date_time = datetime.now().strftime("%Y%m%d%H%M%S")
print(f"Sekarang Tanggal dan Waktunya adalah {date_time}")
print("Nama Saya Falih")
print("Update 1")
print("Update 2")
print("Update 3")
print("Update 4")
print("Update 5")
print("Update 6")
print("Update 7")
print("Update 8")
print("Update 9")
print("Update 10")
print("Update 11")
print("Update 12")
print("Update 13")
print("Update 14")
print("Update 15")
print("Update 16")
print("Update 17")
print("Update 18")
print("Update 19")
print("Update 20")
